# Generated by Django 3.2.6 on 2022-11-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0003_auto_20221116_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
