# Generated by Django 3.2.6 on 2022-11-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0004_auto_20221117_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
