# Generated by Django 4.0.3 on 2022-10-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Anouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Website Address')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.IntegerField(default=773733, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('phone_num', models.CharField(default='-1', max_length=12)),
                ('date', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.URLField(verbose_name='File type')),
                ('filePath', models.URLField(verbose_name='File path')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('rating', models.CharField(blank=True, max_length=2, null=True, verbose_name='Rating')),
                ('programs', models.CharField(blank=True, max_length=40, null=True, verbose_name='Programs')),
                ('lender_FHA_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender FHA ID')),
                ('lender_VA_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender VA ID')),
                ('account_executive', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Executive')),
                ('phone_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Website Address')),
            ],
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.IntegerField(default=479383, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RecentBorrowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date')),
                ('fname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='RecentLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date')),
                ('fname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, verbose_name='Status')),
                ('id', models.IntegerField(default=1087, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20)),
                ('uID', models.IntegerField(default=0)),
                ('fName', models.CharField(default='', max_length=40)),
                ('lName', models.CharField(default='', max_length=40)),
                ('nmlsID', models.IntegerField(default=0)),
                ('ssn', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.IntegerField(default=249425, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('announcements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anouncements')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.files')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.media')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.news')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(blank=True, max_length=40, null=True)),
                ('mileStone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oTitle', models.CharField(blank=True, max_length=40, null=True)),
                ('mileStone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('caseId', models.IntegerField(default=766118, primary_key=True, serialize=False, unique=True, verbose_name='Case ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('fName', models.CharField(blank=True, max_length=40, null=True)),
                ('lName', models.CharField(blank=True, max_length=40, null=True)),
                ('creditScore', models.IntegerField(default=836092, unique=True, verbose_name='Credit Score')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_num', models.CharField(max_length=16, null=True, verbose_name='Phone Number')),
                ('resources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resources')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cID', models.IntegerField(default=396668, unique=True)),
                ('fName', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lName', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_num', models.CharField(max_length=16, null=True, verbose_name='Phone Number')),
                ('resources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resources')),
            ],
        ),
    ]
