# Generated by Django 4.0.3 on 2022-04-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('uID', models.IntegerField(default=845714, unique=True)),
                ('fName', models.CharField(blank=True, max_length=40, null=True)),
                ('lName', models.CharField(blank=True, max_length=40, null=True)),
                ('nmlsID', models.IntegerField(default=907936, unique=True)),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lname',
        ),
        migrations.AddField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=132471, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
