# Generated by Django 4.0.3 on 2022-04-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_cid_alter_user_nmlsid_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Website Address')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.URLField(verbose_name='File type')),
                ('filePath', models.URLField(verbose_name='File path')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Website Address')),
            ],
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.IntegerField(default=909295, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, verbose_name='Status')),
                ('id', models.IntegerField(default=957831, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=517995, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=185723, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=581735, unique=True),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.IntegerField(default=649813, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('announcements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anouncements')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.files')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.media')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.news')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(blank=True, max_length=40, null=True)),
                ('mileStone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oTitle', models.CharField(blank=True, max_length=40, null=True)),
                ('mileStone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditScore', models.IntegerField(default=822634, unique=True, verbose_name='Credit Score')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resources'),
        ),
        migrations.AddField(
            model_name='user',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resources'),
        ),
    ]
