# Generated by Django 4.1.2 on 2022-10-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20221010_0024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="caseId",
            field=models.IntegerField(
                default=434215,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="creditScore",
            field=models.IntegerField(
                default=944095, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cID",
            field=models.IntegerField(default=358376, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="caseId",
            field=models.IntegerField(
                default=191577,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="creditScore",
            field=models.IntegerField(
                default=895026, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="id",
            field=models.IntegerField(
                default=694676,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="id",
            field=models.IntegerField(
                default=929686,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(default=252667, unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                blank=True,
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Status",
            ),
        ),
    ]
