# Generated by Django 4.0.3 on 2022-10-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lenderlogo_logo_alter_borrower_caseid_and_more'),
        ('api', '0010_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
    ]

    operations = [
    ]
