<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-09 22:00
=======
# Generated by Django 4.0.3 on 2022-05-06 23:13
>>>>>>> origin/alpha

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220426_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cID',
<<<<<<< HEAD
            field=models.IntegerField(default=326899, unique=True),
=======
            field=models.IntegerField(default=196594, unique=True),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
<<<<<<< HEAD
            field=models.IntegerField(default=690002, unique=True, verbose_name='Credit Score'),
=======
            field=models.IntegerField(default=506642, unique=True, verbose_name='Credit Score'),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=242396, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=167709, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=633763, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=148030, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=933048, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=107222, unique=True, verbose_name='ID'),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
<<<<<<< HEAD
            field=models.IntegerField(default=670897, unique=True),
=======
            field=models.IntegerField(default=598799, unique=True),
>>>>>>> origin/alpha
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
<<<<<<< HEAD
            field=models.IntegerField(default=940835, unique=True),
=======
            field=models.IntegerField(default=175434, unique=True),
>>>>>>> origin/alpha
        ),
    ]
