# Generated by Django 4.0.3 on 2022-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_client_cid_alter_lead_creditscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='creditScore',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='borrower',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='fname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='lname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone_num',
            field=models.CharField(default='-1', max_length=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fico',
            field=models.IntegerField(default=679939, unique=True, verbose_name='Fico Score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(default='-1', max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='lname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_num',
            field=models.CharField(default='-1', max_length=12),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.IntegerField(default=637125, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=28167, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.IntegerField(default=180909, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=283524, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=124082, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=774679, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=698767, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=701753, unique=True),
        ),
    ]
