# Generated by Django 4.0.3 on 2022-10-13 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentborrowers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recentleads',
            name='id',
        ),
        migrations.AddField(
            model_name='recentborrowers',
            name='caseId',
            field=models.IntegerField(default=394454, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AddField(
            model_name='recentborrowers',
            name='phone_num',
            field=models.CharField(max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='recentleads',
            name='caseId',
            field=models.IntegerField(default=100449, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AddField(
            model_name='recentleads',
            name='phone_num',
            field=models.CharField(max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='caseId',
            field=models.IntegerField(default=772028, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='creditScore',
            field=models.IntegerField(default=217792, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=642437, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=323053, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
            field=models.IntegerField(default=776156, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=989861, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recentborrowers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='recentleads',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=974737, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=720004, unique=True, verbose_name='ID'),
        ),
    ]
