# Generated by Django 3.2.6 on 2022-11-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20221117_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucements',
            new_name='Announcements',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='caseId',
            field=models.IntegerField(default=115372, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='creditScore',
            field=models.IntegerField(null=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('Application_Complete', 'Application Complete'), ('AUS_Cleared', 'AUS Cleared'), ('Initial_Disclosure_Sent', 'Initial Disclosure Sent'), ('Title_Ordered', 'Title Ordered'), ('Title_Recieved', 'Title Recieved'), ('Appraisal_Ordered', 'Appraisal Ordered'), ('Appraisal_Recieved', 'Appraisal Recieved'), ('Initial_Disclosure_Recieved', 'Initial Disclosure Recieved'), ('UW_Submitted', 'UW Submitted'), ('UW_Response', 'UW Response'), ('Pending_Conditions', 'Pending Conditions'), ('Cleared_To_Close', 'Cleared To Close'), ('Closing_Package_Sent', 'Closing Package Sent'), ('New', 'New'), ('Closed', 'Closed'), ('In_Progress', 'In Progress')], max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=922894, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=690738, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Application_Complete', 'Application Complete'), ('Recently_Added', 'Recently Added'), ('Contacted', 'Contacted'), ('Closed', 'Closed'), ('Declined', 'Declined'), ('In_Progress', 'In Progress'), ('Missing_Paperwork', 'Missing Paperwork')], max_length=40),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=744308, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recyclingbin',
            name='caseId',
            field=models.IntegerField(default=667803, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='recyclingbin',
            name='trashID',
            field=models.IntegerField(default=339109, primary_key=True, serialize=False, unique=True, verbose_name='trash ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=148689, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, max_length=200, verbose_name='Account Information')),
                ('ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
