# Generated by Django 4.1.1 on 2022-09-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_client_cid_alter_lead_creditscore_and_more'),
        ('api', '0014_alter_borrower_id_alter_client_cid_alter_lead_fico_and_more'),
        ('api', '0029_alter_client_cid_alter_lead_caseid_and_more'),
    ]

    operations = [
    ]
