# Generated by Django 4.1.1 on 2022-09-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20220918_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='fico',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lname',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.IntegerField(default=116806, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=468686, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=526378, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
            field=models.IntegerField(default=189460, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_num',
            field=models.CharField(max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=639870, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=668610, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=309582, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=595380, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=357145, unique=True),
        ),
    ]
