# Generated by Django 4.1.2 on 2022-11-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_borrower_caseid_alter_borrower_creditscore_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="lender", name="state",),
        migrations.AlterField(
            model_name="borrower",
            name="caseId",
            field=models.IntegerField(
                default=475483,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="creditScore",
            field=models.IntegerField(
                default=980725, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cID",
            field=models.IntegerField(default=625397, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="caseId",
            field=models.IntegerField(
                default=919982,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="id",
            field=models.IntegerField(
                default=125275,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="caseId",
            field=models.IntegerField(default=235614, verbose_name="Case ID"),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="trashID",
            field=models.IntegerField(
                default=729349,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="trash ID",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="id",
            field=models.IntegerField(
                default=116382,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(default=10956, unique=True, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="AccountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Account Information"
                    ),
                ),
                (
                    "ssn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userprofile",
                    ),
                ),
            ],
        ),
    ]
