# Generated by Django 4.1.2 on 2022-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_remove_lender_state_alter_borrower_caseid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="caseId",
            field=models.IntegerField(
                default=570633,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="creditScore",
            field=models.IntegerField(
                default=632521, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cID",
            field=models.IntegerField(default=821786, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="caseId",
            field=models.IntegerField(
                default=297171,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="id",
            field=models.IntegerField(
                default=614080,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="caseId",
            field=models.IntegerField(default=318817, verbose_name="Case ID"),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="trashID",
            field=models.IntegerField(
                default=441604,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="trash ID",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="id",
            field=models.IntegerField(
                default=744729,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(default=649005, unique=True, verbose_name="ID"),
        ),
    ]
