# Generated by Django 4.0.3 on 2022-11-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
        ('api', '0032_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
    ]

    operations = [
    ]
