# Generated by Django 4.0.3 on 2022-11-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
        ('api', '0033_merge_20221107_0624'),
    ]

    operations = [
    ]
