# Generated by Django 4.0.3 on 2022-10-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0038_alter_borrower_id_alter_client_cid_alter_lead_caseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('rating', models.CharField(blank=True, max_length=2, null=True, verbose_name='Rating')),
                ('programs', models.CharField(blank=True, max_length=40, null=True, verbose_name='Programs')),
                ('lender_FHA_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender FHA ID')),
                ('lender_VA_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender VA ID')),
                ('account_executive', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Executive')),
                ('phone_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='RecentLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date')),
                ('fname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20)),
                ('uID', models.IntegerField(default=0)),
                ('fName', models.CharField(default='', max_length=40)),
                ('lName', models.CharField(default='', max_length=40)),
                ('nmlsID', models.IntegerField(default=0)),
                ('ssn', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.IntegerField(default=77168, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=8771, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=379484, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
            field=models.IntegerField(default=381840, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=160272, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=269140, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=552937, unique=True, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
