<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-09-20 00:27
=======
# Generated by Django 4.0.3 on 2022-09-21 17:26
>>>>>>> alpha

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('api', '0041_alter_borrower_id_alter_client_cid_alter_lead_caseid_and_more'),
=======
        ('api', '0041_lender_alter_borrower_id_alter_client_cid_and_more'),
>>>>>>> alpha
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=232833, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=893474, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
<<<<<<< HEAD
            field=models.IntegerField(default=263915, unique=True),
=======
            field=models.IntegerField(default=262433, unique=True),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
<<<<<<< HEAD
            field=models.IntegerField(default=720353, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
=======
            field=models.IntegerField(default=40100, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
<<<<<<< HEAD
            field=models.IntegerField(default=54836, unique=True, verbose_name='Credit Score'),
=======
            field=models.IntegerField(default=347033, unique=True, verbose_name='Credit Score'),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=821033, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=568105, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=380812, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=230566, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
>>>>>>> alpha
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
<<<<<<< HEAD
            field=models.IntegerField(default=458067, unique=True, verbose_name='ID'),
=======
            field=models.IntegerField(default=910900, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=696673, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=237159, unique=True),
>>>>>>> alpha
        ),
    ]
