# Generated by Django 4.0.3 on 2022-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_annoucements_alter_borrower_id_alter_client_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='lender',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='lender',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.IntegerField(default=863323, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=303094, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=331085, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
            field=models.IntegerField(default=115492, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=795942, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=708232, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=464056, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=806728, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=975960, unique=True),
        ),
    ]
