# Generated by Django 4.1.2 on 2022-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_images_alter_borrower_caseid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="caseId",
            field=models.IntegerField(
                default=781220,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="creditScore",
            field=models.IntegerField(
                default=898849, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cID",
            field=models.IntegerField(default=952629, unique=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="id",
            field=models.IntegerField(
                default=880260,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="id",
            field=models.IntegerField(
                default=77330,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="caseId",
            field=models.IntegerField(
                default=514136,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="id",
            field=models.IntegerField(
                default=968547,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="caseId",
            field=models.IntegerField(default=551490, verbose_name="Case ID"),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="trashID",
            field=models.IntegerField(
                default=540944,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="trash ID",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="id",
            field=models.IntegerField(
                default=648603,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(
                default=34223,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Lead",
                        (
                            ("Application_Complete", "Application Complete"),
                            ("Recently_Added", "Recently Added"),
                            ("Contacted", "Contacted"),
                            ("Declined", "Declined"),
                            ("In_Progress", "In Progress"),
                            ("Missing_Paperwork", "Missing Paperwork"),
                            ("Move_to_Borrower", "Move to Borrower"),
                        ),
                    ),
                    (
                        "Borrower",
                        (
                            ("Application_Complete", "Application Complete"),
                            ("AUS_Cleared", "AUS Cleared"),
                            ("Initial_Disclosure_Sent", "Initial Disclosure Sent"),
                            ("Title_Ordered", "Title Ordered"),
                            ("Title_Recieved", "Title Recieved"),
                            ("Appraisal_Ordered", "Appraisal Ordered"),
                            ("Appraisal_Recieved", "Appraisal Recieved"),
                            (
                                "Initial_Disclosure_Recieved",
                                "Initial Disclosure Recieved",
                            ),
                            ("UW_Submitted", "UW Submitted"),
                            ("UW_Response", "UW Response"),
                            ("Pending_Conditions", "Pending Conditions"),
                            ("Cleared_To_Close", "Cleared To Close"),
                            ("Closing_Package_Sent", "Closing Package Sent"),
                        ),
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.IntegerField(
                default=360794,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
