# Generated by Django 4.0.3 on 2022-09-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_lender_email_remove_lender_phone_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='account_executive',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Executive'),
        ),
        migrations.AddField(
            model_name='lender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lender',
            name='lender_FHA_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender FHA ID'),
        ),
        migrations.AddField(
            model_name='lender',
            name='lender_VA_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lender VA ID'),
        ),
        migrations.AddField(
            model_name='lender',
            name='phone_num',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.IntegerField(default=612703, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cID',
            field=models.IntegerField(default=933271, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='caseId',
            field=models.IntegerField(default=22471, primary_key=True, serialize=False, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditScore',
            field=models.IntegerField(default=448715, unique=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.IntegerField(default=920875, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.IntegerField(default=569832, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=751701, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nmlsID',
            field=models.IntegerField(default=378209, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.IntegerField(default=664929, unique=True),
        ),
    ]
