# Generated by Django 4.1.2 on 2022-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_borrower_caseid_alter_borrower_creditscore_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="caseId",
            field=models.IntegerField(
                default=244079,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="creditScore",
            field=models.IntegerField(
                default=272410, unique=True, verbose_name="Credit Score"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cID",
            field=models.IntegerField(default=944902, unique=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="id",
            field=models.IntegerField(
                default=636400,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="id",
            field=models.IntegerField(
                default=558062,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="caseId",
            field=models.IntegerField(
                default=76528,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="id",
            field=models.IntegerField(
                default=571646,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="caseId",
            field=models.IntegerField(default=331933, verbose_name="Case ID"),
        ),
        migrations.AlterField(
            model_name="recyclingbin",
            name="trashID",
            field=models.IntegerField(
                default=777924,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="trash ID",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="id",
            field=models.IntegerField(
                default=590009,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(
                default=970333,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.IntegerField(
                default=623669,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
