# Generated by Django 4.0.3 on 2022-12-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
        ('api', '0112_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
    ]

    operations = [
    ]
