# Generated by Django 4.0.3 on 2022-12-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
        ('api', '0113_merge_20221201_0400'),
    ]

    operations = [
    ]
