# Generated by Django 4.0.3 on 2022-12-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_merge_20221204_0429'),
        ('api', '0115_alter_borrower_caseid_alter_borrower_creditscore_and_more'),
    ]

    operations = [
    ]
