# Generated by Django 4.0.3 on 2022-11-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_loan_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_loan_processor',
            field=models.BooleanField(default=False),
        ),
    ]
