# Generated by Django 4.0.3 on 2022-11-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_loan_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_loan_officer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_loan_processor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Loan Processor', 'Loan Processor'), ('Loan Officer', 'Loan Officer')], default='', max_length=40),
        ),
    ]
