# Generated by Django 4.0.3 on 2022-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='milestone_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
